### ISSUE TITLE
Handler doesnt contain any handles

### ISSUE THREAD

**Issue by ChannelUndefined** [Lux-0/GearV2#1]
This handler doesn't have any handles. Where the fuck am I supposed to grab onto? I thought this was meant to be a handler, but there's no handles. LET ME GRAB

**Comment by ChannelUndefined** [comment]
bro reply to my shit you dipshit

**Comment by ChannelUndefined** [comment]
im about to mississippi queen you mf

**Comment by Lux-0** [comment]
Does not need handles idot

**Comment by ChannelUndefined** [comment]
fuck you
